// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v7.36.1
// source: meshtastic/field_metadata.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Structured, app/UI-relevant metadata describing a protobuf field or enum value.
//
// Carried in a single FieldOptions extension (`field_metadata` below), so adding
// an attribute is a SCHEMA-ONLY change: add a new field to this message (use the
// next field number) and every generated registry - KMP/Wire, C, Python,
// TypeScript, Rust, Swift - picks it up automatically. No generator code change
// is needed, and no additional FieldOptions extension number is consumed.
//
// The one build step an attribute addition does cost is regenerating
// protoc-gen-fieldmeta-swift's own binding for this file
// (tools/protoc-gen-fieldmeta-swift/README.md documents the one-liner). That
// plugin decodes the option through a generated Swift type rather than through
// dynamic reflection as the Go plugin does, so a stale binding cannot see the
// new attribute. It fails loudly rather than dropping it silently.
//
// Constraint: attributes must be SCALAR (bool / 32-bit int / float / string).
// A message, enum, bytes, repeated, or map attribute is rejected at generation
// time (the generators would otherwise emit meaningless, non-deterministic
// values), and so is a 64-bit integer kind, which TypeScript's number cannot
// hold exactly. Float attributes must be finite: an open bound is left unset,
// not set to inf. A list is therefore a single delimited string - see
// `keywords`. See tools/protoc-gen-fieldmeta.
//
// BOUNDS (`min_value`, `max_value`) are PRESENTATION metadata, deliberately, and
// they overlap an existing standard. protovalidate - `(buf.validate.field)`,
// buf's successor to protoc-gen-validate - is the industry-standard way to
// express a numeric constraint in a schema, and where a constraint must be
// ENFORCED that is the thing to reach for, not these two attributes.
//
// They exist here anyway because protovalidate evaluates CEL against a
// descriptor at runtime, and the consumers that most need a bound cannot do
// that: nanopb on the firmware has no descriptors and no CEL, and neither do
// the generated Wire, prost or swift-protobuf types the clients use. A build-
// time attribute is the only form that reaches every target.
//
// The cost is that a bound stated here and a bound enforced elsewhere can
// drift, and nothing detects it. So: state a bound here only when the firmware
// genuinely enforces it, treat the firmware as the source of truth, and if
// `(buf.validate.field)` is ever adopted for a field, make these mirror it
// rather than compete with it.
//
// STRING attributes are treated as user-facing display text and are emitted for
// localization where the target supports it - the Swift target emits
// String(localized:defaultValue:comment:) keyed by the field's full name, so the
// English here is the SOURCE string and translations live in the consuming app's
// catalog. Do not put machine-readable values (regexes, identifiers, format
// codes) in a string attribute; they would be handed to translators.
//
// The exception is a short, named set of MACHINE-READABLE string attributes -
// currently `since_firmware` and `deprecated_since` - which the generators emit
// as plain literals. A firmware version is compared rather than read, and a
// translated one would compare wrongly at runtime. The set is deliberately
// closed and lives in the generators (`machineReadableAttributes`); adding to it
// is a generator change and should stay rare, because every entry is a string a
// translator will never see and therefore a place display text can hide.
//
// To tag a field, set the option on it, e.g.
//
//	uint32 rx_gpio = 8 [(meshtastic.field_metadata) = { diy_only: true }];
//
// One attribute, `deprecated`, is special: it MIRRORS the field's standard
// `[deprecated = true]` option rather than being set inside this annotation.
// The generators populate it from that standard option so apps can read
// deprecation at runtime (protobuf runtimes strip options, so it is otherwise
// invisible). This is the only attribute that costs a generator change.
//
// Downstream apps use this to drive UI decisions (e.g. hiding DIY-only settings
// on pre-assembled boards) directly from the protobuf schema.
type FieldMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Field is only relevant to DIY hardware builds. Apps may hide it when
	// connected to a pre-assembled / commercial board.
	DiyOnly *bool `protobuf:"varint,1,opt,name=diy_only,json=diyOnly" json:"diy_only,omitempty"`
	// Field is only relevant in advanced / administrative contexts and may be
	// hidden from the default UI.
	AdminOnly *bool `protobuf:"varint,2,opt,name=admin_only,json=adminOnly" json:"admin_only,omitempty"`
	// Inclusive lower bound, for PRESENTATION: slider and stepper range, and the
	// client-side check that stops a user entering a value the firmware would
	// reject anyway. It is NOT the wire contract and nothing enforces it on
	// receipt - see the note on bounds below.
	MinValue *float64 `protobuf:"fixed64,3,opt,name=min_value,json=minValue" json:"min_value,omitempty"`
	// Inclusive upper bound, for PRESENTATION. Same status as `min_value`.
	MaxValue *float64 `protobuf:"fixed64,4,opt,name=max_value,json=maxValue" json:"max_value,omitempty"`
	// Human-facing unit label for the value (e.g. "m", "s", "dBm").
	Unit *string `protobuf:"bytes,5,opt,name=unit" json:"unit,omitempty"`
	// Field is deprecated. MIRRORS the field's standard `[deprecated = true]`
	// option - the generators populate this automatically from that option so
	// every consumer can read it at runtime (protobuf runtimes strip options, so
	// the standard `deprecated` bit is otherwise invisible to apps). Setting it
	// by hand in a (meshtastic.field_metadata) annotation is a generation-time
	// ERROR; mark the field `[deprecated = true]` as usual and it flows through
	// here.
	Deprecated *bool `protobuf:"varint,6,opt,name=deprecated" json:"deprecated,omitempty"`
	// Short human-facing name for the field, as a UI would label the control that
	// edits it (e.g. "Hop Limit"). Source string for localization; see the note on
	// string attributes above.
	Label *string `protobuf:"bytes,7,opt,name=label" json:"label,omitempty"`
	// One-sentence plain-language explanation of what the field does, suitable for
	// showing under the control (e.g. "How many times a message may be repeated
	// before it stops being forwarded."). Source string for localization.
	Description *string `protobuf:"bytes,8,opt,name=description" json:"description,omitempty"`
	// Additional terms a user might search for to find this field, beyond its
	// label - abbreviations, older names, and related concepts (e.g. for
	// `hop_limit`: "hops|ttl|range"). Attributes must be scalar, so this is a
	// single string; entries are separated by "|" and surrounding whitespace is
	// ignored. "|" is used rather than "," because a keyword may itself contain a
	// comma. Source string for localization.
	Keywords *string `protobuf:"bytes,9,opt,name=keywords" json:"keywords,omitempty"`
	// The first firmware version that has this field, e.g. "2.7.12".
	//
	// A client showing a control for a field the connected node does not have
	// offers a setting that will be ignored; one hiding a field the node does
	// have loses a setting that works. Today each client answers that from a
	// version constant written into its own UI, so the same boundary is stated
	// independently in each of them - and when firmware adds a field, every
	// client has to learn the number separately.
	//
	// MACHINE-READABLE (see the note on string attributes above): a version is
	// compared, not read, and is emitted as a plain literal rather than as
	// localizable text.
	//
	// Presentation metadata, like `min_value`: firmware still has to defend
	// itself, since an older client can always write a field a newer firmware
	// ignores, and a newer client a field an older one does not know.
	//
	// Unset means "as long as anyone needs to care", which is the common case -
	// annotate a field only where a client genuinely has to make this decision.
	SinceFirmware *string `protobuf:"bytes,10,opt,name=since_firmware,json=sinceFirmware" json:"since_firmware,omitempty"`
	// The first firmware version that no longer honours this field, e.g. "2.7.1"
	// on `compass_north_top`: `compass_orientation` replaced it in 2.3.13, but
	// firmware went on reading the old field until 2.7.1. The replacement's
	// arrival and the old field's removal are different releases, which is the
	// whole reason this is worth writing down.
	//
	// Distinct from `deprecated`, which says only THAT a field is superseded.
	// That is enough to stop offering it on new firmware but not enough to keep
	// offering it where it still works: a node below this version needs the field,
	// and a client that hides it on the strength of the boolean alone takes a
	// working setting away. Both clients do exactly that today.
	//
	// So the intended rule is: show the field below this version; at or above it,
	// treat it as `deprecated` does - hidden unless the node holds a non-default
	// value, which keeps a stale setting visible rather than silently saved.
	//
	// Deprecated is not removed. A field firmware has stopped reading entirely is
	// a different statement and wants its own annotation rather than this one.
	//
	// MACHINE-READABLE, and presentation metadata, on the same terms as
	// `since_firmware`.
	DeprecatedSince *string `protobuf:"bytes,11,opt,name=deprecated_since,json=deprecatedSince" json:"deprecated_since,omitempty"`
}

func (x *FieldMetadata) Reset() {
	*x = FieldMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshtastic_field_metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldMetadata) ProtoMessage() {}

func (x *FieldMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_field_metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldMetadata.ProtoReflect.Descriptor instead.
func (*FieldMetadata) Descriptor() ([]byte, []int) {
	return file_meshtastic_field_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *FieldMetadata) GetDiyOnly() bool {
	if x != nil && x.DiyOnly != nil {
		return *x.DiyOnly
	}
	return false
}

func (x *FieldMetadata) GetAdminOnly() bool {
	if x != nil && x.AdminOnly != nil {
		return *x.AdminOnly
	}
	return false
}

func (x *FieldMetadata) GetMinValue() float64 {
	if x != nil && x.MinValue != nil {
		return *x.MinValue
	}
	return 0
}

func (x *FieldMetadata) GetMaxValue() float64 {
	if x != nil && x.MaxValue != nil {
		return *x.MaxValue
	}
	return 0
}

func (x *FieldMetadata) GetUnit() string {
	if x != nil && x.Unit != nil {
		return *x.Unit
	}
	return ""
}

func (x *FieldMetadata) GetDeprecated() bool {
	if x != nil && x.Deprecated != nil {
		return *x.Deprecated
	}
	return false
}

func (x *FieldMetadata) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

func (x *FieldMetadata) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *FieldMetadata) GetKeywords() string {
	if x != nil && x.Keywords != nil {
		return *x.Keywords
	}
	return ""
}

func (x *FieldMetadata) GetSinceFirmware() string {
	if x != nil && x.SinceFirmware != nil {
		return *x.SinceFirmware
	}
	return ""
}

func (x *FieldMetadata) GetDeprecatedSince() string {
	if x != nil && x.DeprecatedSince != nil {
		return *x.DeprecatedSince
	}
	return ""
}

var file_meshtastic_field_metadata_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldMetadata)(nil),
		Field:         51001,
		Name:          "meshtastic.field_metadata",
		Tag:           "bytes,51001,opt,name=field_metadata",
		Filename:      "meshtastic/field_metadata.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*FieldMetadata)(nil),
		Field:         51001,
		Name:          "meshtastic.enum_value_metadata",
		Tag:           "bytes,51001,opt,name=enum_value_metadata",
		Filename:      "meshtastic/field_metadata.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// Attach FieldMetadata to a field, e.g.
	//
	//	uint32 rx_gpio = 8 [(meshtastic.field_metadata) = { diy_only: true }];
	//
	// Private-use extension number range is 50000-99999.
	//
	// optional meshtastic.FieldMetadata field_metadata = 51001;
	E_FieldMetadata = &file_meshtastic_field_metadata_proto_extTypes[0]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// Attach the same metadata to an ENUM VALUE, e.g.
	//
	//	LONG_FAST = 0 [(meshtastic.enum_value_metadata) = { label: "Long Range - Fast" }];
	//
	// A picker's options are enum values, so this is what gives them display text:
	// without it every client hand-maintains its own copy of "Long Range - Fast",
	// "United States" and the rest, and they drift. Bitfield flags are enum values
	// too, which is how a single uint32 field like PositionConfig.position_flags
	// can name the individual toggles that make it up.
	//
	// Reuses the FieldMetadata message so there is one shape, one registry and one
	// localization path for both. Attributes that only make sense for a numeric
	// field (min_value, max_value, unit) are simply left unset.
	//
	// Extension numbers are scoped per extendee, so sharing 51001 with the
	// FieldOptions extension above is deliberate and not a conflict.
	//
	// optional meshtastic.FieldMetadata enum_value_metadata = 51001;
	E_EnumValueMetadata = &file_meshtastic_field_metadata_proto_extTypes[1]
)

var File_meshtastic_field_metadata_proto protoreflect.FileDescriptor

var file_meshtastic_field_metadata_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2f, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x1a, 0x20, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xdd, 0x02, 0x0a, 0x0d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x69, 0x79, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x69, 0x79, 0x4f, 0x6e, 0x6c, 0x79, 0x12, 0x1d, 0x0a, 0x0a,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x4f, 0x6e, 0x6c, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x6d,
	0x69, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08,
	0x6d, 0x69, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6d, 0x61, 0x78,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x70,
	0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x64,
	0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x25, 0x0a,
	0x0e, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x5f, 0x66, 0x69, 0x72, 0x6d, 0x77, 0x61, 0x72, 0x65, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x46, 0x69, 0x72, 0x6d,
	0x77, 0x61, 0x72, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x53, 0x69, 0x6e, 0x63, 0x65, 0x3a,
	0x61, 0x0a, 0x0e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0xb9, 0x8e, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x74,
	0x61, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x52, 0x0d, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x3a, 0x6e, 0x0a, 0x13, 0x65, 0x6e, 0x75, 0x6d, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x21, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6e, 0x75, 0x6d,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xb9, 0x8e, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69,
	0x63, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52,
	0x11, 0x65, 0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x42, 0x69, 0x0a, 0x14, 0x6f, 0x72, 0x67, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61,
	0x73, 0x74, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x13, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x5a,
	0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x73, 0x68,
	0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2f, 0x67, 0x6f, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x64, 0xaa, 0x02, 0x14, 0x4d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0xba, 0x02, 0x00,
}

var (
	file_meshtastic_field_metadata_proto_rawDescOnce sync.Once
	file_meshtastic_field_metadata_proto_rawDescData = file_meshtastic_field_metadata_proto_rawDesc
)

func file_meshtastic_field_metadata_proto_rawDescGZIP() []byte {
	file_meshtastic_field_metadata_proto_rawDescOnce.Do(func() {
		file_meshtastic_field_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_meshtastic_field_metadata_proto_rawDescData)
	})
	return file_meshtastic_field_metadata_proto_rawDescData
}

var file_meshtastic_field_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_meshtastic_field_metadata_proto_goTypes = []interface{}{
	(*FieldMetadata)(nil),                 // 0: meshtastic.FieldMetadata
	(*descriptorpb.FieldOptions)(nil),     // 1: google.protobuf.FieldOptions
	(*descriptorpb.EnumValueOptions)(nil), // 2: google.protobuf.EnumValueOptions
}
var file_meshtastic_field_metadata_proto_depIdxs = []int32{
	1, // 0: meshtastic.field_metadata:extendee -> google.protobuf.FieldOptions
	2, // 1: meshtastic.enum_value_metadata:extendee -> google.protobuf.EnumValueOptions
	0, // 2: meshtastic.field_metadata:type_name -> meshtastic.FieldMetadata
	0, // 3: meshtastic.enum_value_metadata:type_name -> meshtastic.FieldMetadata
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meshtastic_field_metadata_proto_init() }
func file_meshtastic_field_metadata_proto_init() {
	if File_meshtastic_field_metadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meshtastic_field_metadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meshtastic_field_metadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_meshtastic_field_metadata_proto_goTypes,
		DependencyIndexes: file_meshtastic_field_metadata_proto_depIdxs,
		MessageInfos:      file_meshtastic_field_metadata_proto_msgTypes,
		ExtensionInfos:    file_meshtastic_field_metadata_proto_extTypes,
	}.Build()
	File_meshtastic_field_metadata_proto = out.File
	file_meshtastic_field_metadata_proto_rawDesc = nil
	file_meshtastic_field_metadata_proto_goTypes = nil
	file_meshtastic_field_metadata_proto_depIdxs = nil
}
