// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v7.36.1
// source: meshtastic/lorawan_bridge.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Values 0 to 7 mirror the Semtech TX_ACK error field. Keep every value non
// negative; enums encode as int32.
type LoRaWANBridge_TxResult_Status int32

const (
	LoRaWANBridge_TxResult_NONE             LoRaWANBridge_TxResult_Status = 0
	LoRaWANBridge_TxResult_TOO_LATE         LoRaWANBridge_TxResult_Status = 1
	LoRaWANBridge_TxResult_TOO_EARLY        LoRaWANBridge_TxResult_Status = 2
	LoRaWANBridge_TxResult_COLLISION_PACKET LoRaWANBridge_TxResult_Status = 3
	LoRaWANBridge_TxResult_COLLISION_BEACON LoRaWANBridge_TxResult_Status = 4
	LoRaWANBridge_TxResult_TX_FREQ          LoRaWANBridge_TxResult_Status = 5
	LoRaWANBridge_TxResult_TX_POWER         LoRaWANBridge_TxResult_Status = 6
	LoRaWANBridge_TxResult_GPS_UNLOCKED     LoRaWANBridge_TxResult_Status = 7
	// Held by the gateway for a later receive window.
	LoRaWANBridge_TxResult_DEFERRED LoRaWANBridge_TxResult_Status = 8
	// Discarded, either undeferrable or refused by an authorization check.
	LoRaWANBridge_TxResult_DROPPED LoRaWANBridge_TxResult_Status = 9
)

// Enum value maps for LoRaWANBridge_TxResult_Status.
var (
	LoRaWANBridge_TxResult_Status_name = map[int32]string{
		0: "NONE",
		1: "TOO_LATE",
		2: "TOO_EARLY",
		3: "COLLISION_PACKET",
		4: "COLLISION_BEACON",
		5: "TX_FREQ",
		6: "TX_POWER",
		7: "GPS_UNLOCKED",
		8: "DEFERRED",
		9: "DROPPED",
	}
	LoRaWANBridge_TxResult_Status_value = map[string]int32{
		"NONE":             0,
		"TOO_LATE":         1,
		"TOO_EARLY":        2,
		"COLLISION_PACKET": 3,
		"COLLISION_BEACON": 4,
		"TX_FREQ":          5,
		"TX_POWER":         6,
		"GPS_UNLOCKED":     7,
		"DEFERRED":         8,
		"DROPPED":          9,
	}
)

func (x LoRaWANBridge_TxResult_Status) Enum() *LoRaWANBridge_TxResult_Status {
	p := new(LoRaWANBridge_TxResult_Status)
	*p = x
	return p
}

func (x LoRaWANBridge_TxResult_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoRaWANBridge_TxResult_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_meshtastic_lorawan_bridge_proto_enumTypes[0].Descriptor()
}

func (LoRaWANBridge_TxResult_Status) Type() protoreflect.EnumType {
	return &file_meshtastic_lorawan_bridge_proto_enumTypes[0]
}

func (x LoRaWANBridge_TxResult_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoRaWANBridge_TxResult_Status.Descriptor instead.
func (LoRaWANBridge_TxResult_Status) EnumDescriptor() ([]byte, []int) {
	return file_meshtastic_lorawan_bridge_proto_rawDescGZIP(), []int{0, 3, 0}
}

// Payload for LORAWAN_BRIDGE packets. Tunnels raw LoRaWAN PHY payloads and their
// RF metadata so a gateway can reach a network server over a mesh.
type LoRaWANBridge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Variant:
	//
	//	*LoRaWANBridge_Uplink_
	//	*LoRaWANBridge_Downlink_
	//	*LoRaWANBridge_TxResult_
	//	*LoRaWANBridge_Chunk
	Variant isLoRaWANBridge_Variant `protobuf_oneof:"variant"`
}

func (x *LoRaWANBridge) Reset() {
	*x = LoRaWANBridge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshtastic_lorawan_bridge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoRaWANBridge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoRaWANBridge) ProtoMessage() {}

func (x *LoRaWANBridge) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_lorawan_bridge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoRaWANBridge.ProtoReflect.Descriptor instead.
func (*LoRaWANBridge) Descriptor() ([]byte, []int) {
	return file_meshtastic_lorawan_bridge_proto_rawDescGZIP(), []int{0}
}

func (m *LoRaWANBridge) GetVariant() isLoRaWANBridge_Variant {
	if m != nil {
		return m.Variant
	}
	return nil
}

func (x *LoRaWANBridge) GetUplink() *LoRaWANBridge_Uplink {
	if x, ok := x.GetVariant().(*LoRaWANBridge_Uplink_); ok {
		return x.Uplink
	}
	return nil
}

func (x *LoRaWANBridge) GetDownlink() *LoRaWANBridge_Downlink {
	if x, ok := x.GetVariant().(*LoRaWANBridge_Downlink_); ok {
		return x.Downlink
	}
	return nil
}

func (x *LoRaWANBridge) GetTxResult() *LoRaWANBridge_TxResult {
	if x, ok := x.GetVariant().(*LoRaWANBridge_TxResult_); ok {
		return x.TxResult
	}
	return nil
}

func (x *LoRaWANBridge) GetChunk() *LoRaWANBridge_PayloadChunk {
	if x, ok := x.GetVariant().(*LoRaWANBridge_Chunk); ok {
		return x.Chunk
	}
	return nil
}

type isLoRaWANBridge_Variant interface {
	isLoRaWANBridge_Variant()
}

type LoRaWANBridge_Uplink_ struct {
	Uplink *LoRaWANBridge_Uplink `protobuf:"bytes,1,opt,name=uplink,proto3,oneof"`
}

type LoRaWANBridge_Downlink_ struct {
	Downlink *LoRaWANBridge_Downlink `protobuf:"bytes,2,opt,name=downlink,proto3,oneof"`
}

type LoRaWANBridge_TxResult_ struct {
	TxResult *LoRaWANBridge_TxResult `protobuf:"bytes,3,opt,name=tx_result,json=txResult,proto3,oneof"`
}

type LoRaWANBridge_Chunk struct {
	Chunk *LoRaWANBridge_PayloadChunk `protobuf:"bytes,4,opt,name=chunk,proto3,oneof"`
}

func (*LoRaWANBridge_Uplink_) isLoRaWANBridge_Variant() {}

func (*LoRaWANBridge_Downlink_) isLoRaWANBridge_Variant() {}

func (*LoRaWANBridge_TxResult_) isLoRaWANBridge_Variant() {}

func (*LoRaWANBridge_Chunk) isLoRaWANBridge_Variant() {}

// An uplink heard by the gateway, travelling towards the network server.
type LoRaWANBridge_Uplink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Receive frequency in Hz.
	FreqHz uint32 `protobuf:"fixed32,1,opt,name=freq_hz,json=freqHz,proto3" json:"freq_hz,omitempty"`
	// Concentrator receive timestamp in microseconds. Free running, wraps about
	// every 72 minutes.
	Tmst uint32 `protobuf:"fixed32,2,opt,name=tmst,proto3" json:"tmst,omitempty"`
	// Received signal strength in tenths of a dBm. Fits signed 16 bit.
	RssiX10 int32 `protobuf:"zigzag32,3,opt,name=rssi_x10,json=rssiX10,proto3" json:"rssi_x10,omitempty"`
	// Signal to noise ratio in tenths of a dB. Fits signed 16 bit.
	SnrX10 int32 `protobuf:"zigzag32,4,opt,name=snr_x10,json=snrX10,proto3" json:"snr_x10,omitempty"`
	// Packed radio settings, 0 to 255. Meaningless when fsk_bitrate is set.
	//
	//	bits 7-5  0 to 7 for SF5 to SF12
	//	bits 4-2  bandwidth in kHz: 0 125, 1 250, 2 500, 3 203.125, 4 406.25,
	//	          5 812.5, 6 1625, 7 reserved. Codes 0 to 2 are the sub-GHz set
	//	          and 3 to 6 the 2.4 GHz set; the two do not overlap. Any future
	//	          bandwidth takes the next free code rather than sorting in.
	//	bits 1-0  0 to 3 for 4/5 to 4/8
	RadioParams uint32 `protobuf:"varint,5,opt,name=radio_params,json=radioParams,proto3" json:"radio_params,omitempty"`
	// FSK bit rate in bits per second. Non-zero only for an FSK frame, in which
	// case radio_params does not apply. Fits unsigned 16 bit.
	FskBitrate uint32 `protobuf:"varint,9,opt,name=fsk_bitrate,json=fskBitrate,proto3" json:"fsk_bitrate,omitempty"`
	// PHY payload, or its first part when chunk_count is 2.
	Payload []byte `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	// Groups this head with its continuation. 1 to 255, or 0 when not chunked.
	PayloadId uint32 `protobuf:"varint,7,opt,name=payload_id,json=payloadId,proto3" json:"payload_id,omitempty"`
	// 0 when the frame fits one packet, otherwise 2.
	ChunkCount uint32 `protobuf:"varint,8,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
}

func (x *LoRaWANBridge_Uplink) Reset() {
	*x = LoRaWANBridge_Uplink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshtastic_lorawan_bridge_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoRaWANBridge_Uplink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoRaWANBridge_Uplink) ProtoMessage() {}

func (x *LoRaWANBridge_Uplink) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_lorawan_bridge_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoRaWANBridge_Uplink.ProtoReflect.Descriptor instead.
func (*LoRaWANBridge_Uplink) Descriptor() ([]byte, []int) {
	return file_meshtastic_lorawan_bridge_proto_rawDescGZIP(), []int{0, 0}
}

func (x *LoRaWANBridge_Uplink) GetFreqHz() uint32 {
	if x != nil {
		return x.FreqHz
	}
	return 0
}

func (x *LoRaWANBridge_Uplink) GetTmst() uint32 {
	if x != nil {
		return x.Tmst
	}
	return 0
}

func (x *LoRaWANBridge_Uplink) GetRssiX10() int32 {
	if x != nil {
		return x.RssiX10
	}
	return 0
}

func (x *LoRaWANBridge_Uplink) GetSnrX10() int32 {
	if x != nil {
		return x.SnrX10
	}
	return 0
}

func (x *LoRaWANBridge_Uplink) GetRadioParams() uint32 {
	if x != nil {
		return x.RadioParams
	}
	return 0
}

func (x *LoRaWANBridge_Uplink) GetFskBitrate() uint32 {
	if x != nil {
		return x.FskBitrate
	}
	return 0
}

func (x *LoRaWANBridge_Uplink) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *LoRaWANBridge_Uplink) GetPayloadId() uint32 {
	if x != nil {
		return x.PayloadId
	}
	return 0
}

func (x *LoRaWANBridge_Uplink) GetChunkCount() uint32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

// A downlink from the network server, travelling towards the gateway.
type LoRaWANBridge_Downlink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Transmit frequency in Hz.
	FreqHz uint32 `protobuf:"fixed32,1,opt,name=freq_hz,json=freqHz,proto3" json:"freq_hz,omitempty"`
	// Concentrator timestamp to transmit at. Ignored when immediate is set.
	Tmst uint32 `protobuf:"fixed32,2,opt,name=tmst,proto3" json:"tmst,omitempty"`
	// Packed radio settings, encoded as in Uplink.radio_params. FSK downlink is
	// not supported, so there is no bit rate or frequency deviation here.
	RadioParams uint32 `protobuf:"varint,3,opt,name=radio_params,json=radioParams,proto3" json:"radio_params,omitempty"`
	// Transmit power in dBm, 0 to 255. The gateway clamps it to its region.
	PowerDbm uint32 `protobuf:"varint,4,opt,name=power_dbm,json=powerDbm,proto3" json:"power_dbm,omitempty"`
	// Transmit as soon as possible instead of at tmst. Used for Class C.
	Immediate bool `protobuf:"varint,5,opt,name=immediate,proto3" json:"immediate,omitempty"`
	// Invert LoRa polarity. True for every LoRaWAN downlink.
	InvertPolarity bool `protobuf:"varint,6,opt,name=invert_polarity,json=invertPolarity,proto3" json:"invert_polarity,omitempty"`
	// Disable the physical layer CRC.
	NoCrc bool `protobuf:"varint,7,opt,name=no_crc,json=noCrc,proto3" json:"no_crc,omitempty"`
	// Allow the gateway to send this in a later receive window if it arrives too
	// late. Leave clear for anything tied to a specific uplink.
	MayDefer bool `protobuf:"varint,8,opt,name=may_defer,json=mayDefer,proto3" json:"may_defer,omitempty"`
	// Identifies this downlink so its TxResult can be matched to it. 1 to 255.
	RequestId uint32 `protobuf:"varint,12,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// PHY payload, or its first part when chunk_count is 2.
	Payload []byte `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	// Groups this head with its continuation. 1 to 255, or 0 when not chunked.
	PayloadId uint32 `protobuf:"varint,10,opt,name=payload_id,json=payloadId,proto3" json:"payload_id,omitempty"`
	// 0 when the frame fits one packet, otherwise 2.
	ChunkCount uint32 `protobuf:"varint,11,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
}

func (x *LoRaWANBridge_Downlink) Reset() {
	*x = LoRaWANBridge_Downlink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshtastic_lorawan_bridge_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoRaWANBridge_Downlink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoRaWANBridge_Downlink) ProtoMessage() {}

func (x *LoRaWANBridge_Downlink) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_lorawan_bridge_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoRaWANBridge_Downlink.ProtoReflect.Descriptor instead.
func (*LoRaWANBridge_Downlink) Descriptor() ([]byte, []int) {
	return file_meshtastic_lorawan_bridge_proto_rawDescGZIP(), []int{0, 1}
}

func (x *LoRaWANBridge_Downlink) GetFreqHz() uint32 {
	if x != nil {
		return x.FreqHz
	}
	return 0
}

func (x *LoRaWANBridge_Downlink) GetTmst() uint32 {
	if x != nil {
		return x.Tmst
	}
	return 0
}

func (x *LoRaWANBridge_Downlink) GetRadioParams() uint32 {
	if x != nil {
		return x.RadioParams
	}
	return 0
}

func (x *LoRaWANBridge_Downlink) GetPowerDbm() uint32 {
	if x != nil {
		return x.PowerDbm
	}
	return 0
}

func (x *LoRaWANBridge_Downlink) GetImmediate() bool {
	if x != nil {
		return x.Immediate
	}
	return false
}

func (x *LoRaWANBridge_Downlink) GetInvertPolarity() bool {
	if x != nil {
		return x.InvertPolarity
	}
	return false
}

func (x *LoRaWANBridge_Downlink) GetNoCrc() bool {
	if x != nil {
		return x.NoCrc
	}
	return false
}

func (x *LoRaWANBridge_Downlink) GetMayDefer() bool {
	if x != nil {
		return x.MayDefer
	}
	return false
}

func (x *LoRaWANBridge_Downlink) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *LoRaWANBridge_Downlink) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *LoRaWANBridge_Downlink) GetPayloadId() uint32 {
	if x != nil {
		return x.PayloadId
	}
	return 0
}

func (x *LoRaWANBridge_Downlink) GetChunkCount() uint32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

// The remainder of a chunked Uplink or Downlink. Carries no RF metadata.
type LoRaWANBridge_PayloadChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Matches payload_id in the head message. Reassembly keys on the sending
	// node and this value.
	PayloadId uint32 `protobuf:"varint,1,opt,name=payload_id,json=payloadId,proto3" json:"payload_id,omitempty"`
	// Position of this chunk. Always 1.
	ChunkIndex uint32 `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	// This part of the PHY payload.
	PayloadChunk []byte `protobuf:"bytes,3,opt,name=payload_chunk,json=payloadChunk,proto3" json:"payload_chunk,omitempty"`
}

func (x *LoRaWANBridge_PayloadChunk) Reset() {
	*x = LoRaWANBridge_PayloadChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshtastic_lorawan_bridge_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoRaWANBridge_PayloadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoRaWANBridge_PayloadChunk) ProtoMessage() {}

func (x *LoRaWANBridge_PayloadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_lorawan_bridge_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoRaWANBridge_PayloadChunk.ProtoReflect.Descriptor instead.
func (*LoRaWANBridge_PayloadChunk) Descriptor() ([]byte, []int) {
	return file_meshtastic_lorawan_bridge_proto_rawDescGZIP(), []int{0, 2}
}

func (x *LoRaWANBridge_PayloadChunk) GetPayloadId() uint32 {
	if x != nil {
		return x.PayloadId
	}
	return 0
}

func (x *LoRaWANBridge_PayloadChunk) GetChunkIndex() uint32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *LoRaWANBridge_PayloadChunk) GetPayloadChunk() []byte {
	if x != nil {
		return x.PayloadChunk
	}
	return nil
}

// The outcome of a downlink, reported back towards the network server.
type LoRaWANBridge_TxResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The tmst the downlink was scheduled for. Zero when it was immediate, so
	// diagnostic only; correlate on request_id.
	Tmst uint32 `protobuf:"fixed32,1,opt,name=tmst,proto3" json:"tmst,omitempty"`
	// What happened to it.
	Status LoRaWANBridge_TxResult_Status `protobuf:"varint,2,opt,name=status,proto3,enum=meshtastic.LoRaWANBridge_TxResult_Status" json:"status,omitempty"`
	// Echoes Downlink.request_id.
	RequestId uint32 `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (x *LoRaWANBridge_TxResult) Reset() {
	*x = LoRaWANBridge_TxResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshtastic_lorawan_bridge_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoRaWANBridge_TxResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoRaWANBridge_TxResult) ProtoMessage() {}

func (x *LoRaWANBridge_TxResult) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_lorawan_bridge_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoRaWANBridge_TxResult.ProtoReflect.Descriptor instead.
func (*LoRaWANBridge_TxResult) Descriptor() ([]byte, []int) {
	return file_meshtastic_lorawan_bridge_proto_rawDescGZIP(), []int{0, 3}
}

func (x *LoRaWANBridge_TxResult) GetTmst() uint32 {
	if x != nil {
		return x.Tmst
	}
	return 0
}

func (x *LoRaWANBridge_TxResult) GetStatus() LoRaWANBridge_TxResult_Status {
	if x != nil {
		return x.Status
	}
	return LoRaWANBridge_TxResult_NONE
}

func (x *LoRaWANBridge_TxResult) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

var File_meshtastic_lorawan_bridge_proto protoreflect.FileDescriptor

var file_meshtastic_lorawan_bridge_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2f, 0x6c, 0x6f, 0x72,
	0x61, 0x77, 0x61, 0x6e, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x22, 0xb1, 0x0a,
	0x0a, 0x0d, 0x4c, 0x6f, 0x52, 0x61, 0x57, 0x41, 0x4e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x12,
	0x3a, 0x0a, 0x06, 0x75, 0x70, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x4c, 0x6f, 0x52,
	0x61, 0x57, 0x41, 0x4e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x55, 0x70, 0x6c, 0x69, 0x6e,
	0x6b, 0x48, 0x00, 0x52, 0x06, 0x75, 0x70, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x40, 0x0a, 0x08, 0x64,
	0x6f, 0x77, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x4c, 0x6f, 0x52, 0x61, 0x57,
	0x41, 0x4e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x69, 0x6e,
	0x6b, 0x48, 0x00, 0x52, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x41, 0x0a,
	0x09, 0x74, 0x78, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x4c, 0x6f,
	0x52, 0x61, 0x57, 0x41, 0x4e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x54, 0x78, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x08, 0x74, 0x78, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x3e, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x26, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x4c, 0x6f, 0x52,
	0x61, 0x57, 0x41, 0x4e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x48, 0x00, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b,
	0x1a, 0x87, 0x02, 0x0a, 0x06, 0x55, 0x70, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x66,
	0x72, 0x65, 0x71, 0x5f, 0x68, 0x7a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x06, 0x66, 0x72,
	0x65, 0x71, 0x48, 0x7a, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x6d, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x07, 0x52, 0x04, 0x74, 0x6d, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x73, 0x73, 0x69,
	0x5f, 0x78, 0x31, 0x30, 0x18, 0x03, 0x20, 0x01, 0x28, 0x11, 0x52, 0x07, 0x72, 0x73, 0x73, 0x69,
	0x58, 0x31, 0x30, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x6e, 0x72, 0x5f, 0x78, 0x31, 0x30, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x11, 0x52, 0x06, 0x73, 0x6e, 0x72, 0x58, 0x31, 0x30, 0x12, 0x21, 0x0a, 0x0c,
	0x72, 0x61, 0x64, 0x69, 0x6f, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0b, 0x72, 0x61, 0x64, 0x69, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12,
	0x1f, 0x0a, 0x0b, 0x66, 0x73, 0x6b, 0x5f, 0x62, 0x69, 0x74, 0x72, 0x61, 0x74, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x66, 0x73, 0x6b, 0x42, 0x69, 0x74, 0x72, 0x61, 0x74, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x68, 0x75,
	0x6e, 0x6b, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x63, 0x68, 0x75, 0x6e, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0xeb, 0x02, 0x0a, 0x08, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x72, 0x65, 0x71, 0x5f,
	0x68, 0x7a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x06, 0x66, 0x72, 0x65, 0x71, 0x48, 0x7a,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x6d, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x07, 0x52, 0x04,
	0x74, 0x6d, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x61, 0x64, 0x69, 0x6f, 0x5f, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x72, 0x61, 0x64, 0x69,
	0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6f, 0x77, 0x65, 0x72,
	0x5f, 0x64, 0x62, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6f, 0x77, 0x65,
	0x72, 0x44, 0x62, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6d, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x6d, 0x6d, 0x65, 0x64, 0x69, 0x61,
	0x74, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x5f, 0x70, 0x6f, 0x6c,
	0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x69, 0x6e, 0x76,
	0x65, 0x72, 0x74, 0x50, 0x6f, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x12, 0x15, 0x0a, 0x06, 0x6e,
	0x6f, 0x5f, 0x63, 0x72, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6e, 0x6f, 0x43,
	0x72, 0x63, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x79, 0x5f, 0x64, 0x65, 0x66, 0x65, 0x72, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6d, 0x61, 0x79, 0x44, 0x65, 0x66, 0x65, 0x72, 0x12,
	0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x68, 0x75, 0x6e, 0x6b,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x68,
	0x75, 0x6e, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x73, 0x0a, 0x0c, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x68, 0x75, 0x6e, 0x6b,
	0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x68,
	0x75, 0x6e, 0x6b, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0c, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x1a, 0xa6, 0x02,
	0x0a, 0x08, 0x54, 0x78, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x6d,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x04, 0x74, 0x6d, 0x73, 0x74, 0x12, 0x41,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29,
	0x2e, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x4c, 0x6f, 0x52, 0x61,
	0x57, 0x41, 0x4e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x54, 0x78, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64,
	0x22, 0xa3, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x4e,
	0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x4f, 0x4f, 0x5f, 0x4c, 0x41, 0x54,
	0x45, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x4f, 0x4f, 0x5f, 0x45, 0x41, 0x52, 0x4c, 0x59,
	0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x4f, 0x4c, 0x4c, 0x49, 0x53, 0x49, 0x4f, 0x4e, 0x5f,
	0x50, 0x41, 0x43, 0x4b, 0x45, 0x54, 0x10, 0x03, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x4f, 0x4c, 0x4c,
	0x49, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x42, 0x45, 0x41, 0x43, 0x4f, 0x4e, 0x10, 0x04, 0x12, 0x0b,
	0x0a, 0x07, 0x54, 0x58, 0x5f, 0x46, 0x52, 0x45, 0x51, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x54,
	0x58, 0x5f, 0x50, 0x4f, 0x57, 0x45, 0x52, 0x10, 0x06, 0x12, 0x10, 0x0a, 0x0c, 0x47, 0x50, 0x53,
	0x5f, 0x55, 0x4e, 0x4c, 0x4f, 0x43, 0x4b, 0x45, 0x44, 0x10, 0x07, 0x12, 0x0c, 0x0a, 0x08, 0x44,
	0x45, 0x46, 0x45, 0x52, 0x52, 0x45, 0x44, 0x10, 0x08, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x52, 0x4f,
	0x50, 0x50, 0x45, 0x44, 0x10, 0x09, 0x42, 0x09, 0x0a, 0x07, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e,
	0x74, 0x42, 0x69, 0x0a, 0x14, 0x6f, 0x72, 0x67, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73,
	0x74, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x13, 0x4c, 0x6f, 0x52, 0x61, 0x57,
	0x41, 0x4e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x5a, 0x22,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x73, 0x68, 0x74,
	0x61, 0x73, 0x74, 0x69, 0x63, 0x2f, 0x67, 0x6f, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x64, 0xaa, 0x02, 0x14, 0x4d, 0x65, 0x73, 0x68, 0x74, 0x61, 0x73, 0x74, 0x69, 0x63, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0xba, 0x02, 0x00, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meshtastic_lorawan_bridge_proto_rawDescOnce sync.Once
	file_meshtastic_lorawan_bridge_proto_rawDescData = file_meshtastic_lorawan_bridge_proto_rawDesc
)

func file_meshtastic_lorawan_bridge_proto_rawDescGZIP() []byte {
	file_meshtastic_lorawan_bridge_proto_rawDescOnce.Do(func() {
		file_meshtastic_lorawan_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(file_meshtastic_lorawan_bridge_proto_rawDescData)
	})
	return file_meshtastic_lorawan_bridge_proto_rawDescData
}

var file_meshtastic_lorawan_bridge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_meshtastic_lorawan_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_meshtastic_lorawan_bridge_proto_goTypes = []interface{}{
	(LoRaWANBridge_TxResult_Status)(0), // 0: meshtastic.LoRaWANBridge.TxResult.Status
	(*LoRaWANBridge)(nil),              // 1: meshtastic.LoRaWANBridge
	(*LoRaWANBridge_Uplink)(nil),       // 2: meshtastic.LoRaWANBridge.Uplink
	(*LoRaWANBridge_Downlink)(nil),     // 3: meshtastic.LoRaWANBridge.Downlink
	(*LoRaWANBridge_PayloadChunk)(nil), // 4: meshtastic.LoRaWANBridge.PayloadChunk
	(*LoRaWANBridge_TxResult)(nil),     // 5: meshtastic.LoRaWANBridge.TxResult
}
var file_meshtastic_lorawan_bridge_proto_depIdxs = []int32{
	2, // 0: meshtastic.LoRaWANBridge.uplink:type_name -> meshtastic.LoRaWANBridge.Uplink
	3, // 1: meshtastic.LoRaWANBridge.downlink:type_name -> meshtastic.LoRaWANBridge.Downlink
	5, // 2: meshtastic.LoRaWANBridge.tx_result:type_name -> meshtastic.LoRaWANBridge.TxResult
	4, // 3: meshtastic.LoRaWANBridge.chunk:type_name -> meshtastic.LoRaWANBridge.PayloadChunk
	0, // 4: meshtastic.LoRaWANBridge.TxResult.status:type_name -> meshtastic.LoRaWANBridge.TxResult.Status
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_meshtastic_lorawan_bridge_proto_init() }
func file_meshtastic_lorawan_bridge_proto_init() {
	if File_meshtastic_lorawan_bridge_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meshtastic_lorawan_bridge_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoRaWANBridge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshtastic_lorawan_bridge_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoRaWANBridge_Uplink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshtastic_lorawan_bridge_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoRaWANBridge_Downlink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshtastic_lorawan_bridge_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoRaWANBridge_PayloadChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshtastic_lorawan_bridge_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoRaWANBridge_TxResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_meshtastic_lorawan_bridge_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*LoRaWANBridge_Uplink_)(nil),
		(*LoRaWANBridge_Downlink_)(nil),
		(*LoRaWANBridge_TxResult_)(nil),
		(*LoRaWANBridge_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meshtastic_lorawan_bridge_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meshtastic_lorawan_bridge_proto_goTypes,
		DependencyIndexes: file_meshtastic_lorawan_bridge_proto_depIdxs,
		EnumInfos:         file_meshtastic_lorawan_bridge_proto_enumTypes,
		MessageInfos:      file_meshtastic_lorawan_bridge_proto_msgTypes,
	}.Build()
	File_meshtastic_lorawan_bridge_proto = out.File
	file_meshtastic_lorawan_bridge_proto_rawDesc = nil
	file_meshtastic_lorawan_bridge_proto_goTypes = nil
	file_meshtastic_lorawan_bridge_proto_depIdxs = nil
}
